server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kads
    username: kads
    password: kads1234
    driver-class-name: org.postgresql.Driver   # 명시해도 무방 (자동감지 가능)

  jpa:
    hibernate:
      ddl-auto: update                       # 이미 테이블이 있으면 validate 권장 (스키마 보호)
      # 필요 시 update로 바꿔도 됨
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # 강제 지정(자동감지되지만 명시 OK)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace         # 바인딩 파라미터까지 로깅

springdoc:
  swagger-ui:
    path: /swagger-ui.html


  

